[project]
name = "cisco-nso-mcp-server"
version = "0.1.0"
description = "Cisco NSO MCP Server"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "cisco-nso-restconf>=1.0.5",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "python-dotenv>=1.1.0"
]
